EateryZip/src/main/java/com/sixnicorn/eateryzip/filter/loginIFilter.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/Configuration.xml, EateryZip/src/main/webapp/WEB-INF/table.sql
Table.sql에 회원정보 (일반, 비즈니스) 테이블 추가
* 회원정보에 데이터를 입력할 수 있는 insert문 작성해뒀으니 안에 데이터 바꿔서 사용하시면 됩니다.
=> Configuraition.xml에 Alias 요소 추가 , 패키지에 LoginFilter 추가 , 퀀텀DB 테이블 추가,

EateryZip/src/main/webapp/WEB-INF/views/eatery/list.jsp
리스트 페이지 UI - css 일부, js 제외한 상태
=> 리스트 페이지 UI - css 일부, js 제외한 상태

EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/dto/MenuDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/MenuMapper.xml, EateryZip/src/main/webapp/WEB-INF/views/eatery/menu_insertform.jsp
=> pull을 위한 commmit

EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/controller/ListController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/dto/ListDto.java, EateryZip/src/main/webapp/WEB-INF/views/eatery/list.jsp
리스트 페이지 수정, ListController, ListDto 추가
=> 리스트 페이지 수정, ListController, ListDto 추가

EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/controller/MenuController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/dao/MenuDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/dao/MenuDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/dto/MenuDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/service/MenuService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/service/MenuServiceImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/MenuMapper.xml, EateryZip/src/main/webapp/WEB-INF/table.sql, EateryZip/src/main/webapp/WEB-INF/views/users/b_mypage/menu_insertform.jsp
로딩,섹션 폼 추가(기본 구조 셋팅)/메뉴등록,메뉴삭제,카테고리 삭제 ajax 구현/폼유효성검사
자바스크립트 내 삼항연산자 적용 안되는 것 빼고 모두 구현 완료
=> 로딩,섹션 폼 추가(기본 구조 셋팅)/메뉴등록,메뉴삭제,카테고리 삭제 ajax 구현/폼유효성검사

EateryZip/src/main/webapp/WEB-INF/views/eatery/list.jsp
=> list.jsp 데이터 출력 /bootstrap 삭제

EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/UserController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BUserService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BUserServiceImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/users/b_find_id_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_find_pwd_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_login.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_login_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_signup_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_find_id_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_find_pwd_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_login_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_signup_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/map_seoul.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/map_seoul2.jsp
=> 로그인 Cookie 기능 구현 , 서울 지도 동적화

EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/BStoreMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/BStoreController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/store/store_insertform.jsp
다만 check박스부분이 체크가 되지않는다.
수정완료후에 어느페이지로 갈지도 정해야한다.
추가적으로 시간부분도 다시 체크해봐야하고 폼에 입력이 null이면 폼전송이 안되는것도 체크해봐야한다.
=> 가게등록 db에 저장까지 완료

EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/controller/MenuController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/controller/ReservationController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/dao/ReservationDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/dao/ReservationDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/service/ReservationService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/eatery/service/ReservationServiceImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/Configuration.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/ReviewMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/ReviewController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/ReviewDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/ReviewDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/ReservationDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/TakeoutDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/ReviewService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/ReviewServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/table.sql, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/review_takeout_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/takeout_list.jsp
[포장]리뷰 작성 및 수정 구현 완료(이미지 ajax, 키워드 3개 제한 저장 및 수정, 데이터 로딩)/팝업 작업 필요
=> [포장]리뷰 작성 및 수정 구현 완료(이미지 ajax, 키워드 3개 제한 저장 및 수정, 데이터 로딩)/팝업 작업 필요

EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/UserController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/TakeoutDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/users/b_mypage/menu_insertform.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/review_takeout_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/takeout_list.jsp
// 버튼 아이디에 ex) 
// <button type="button" class="takeout_btn" data-takeoutnum="${tmp.takeout_num}" data-id="${tmp.b_id}"> 이런 식으로 만드시고 클릭할 때마다  
// $(.takeout_btn).click(function(){
//	let takeNum=this.attr("data-takeoutnum"); <- 이런식으로 번호 자바스크립트에서 얻어오실 수 있습니다. 이걸 아래의 url에 연결해서 사용하시면 됩니다.
//	let bId=this.attr("data-id");
//window.open("${pageContext.request.contextPath}/users/g_mypage/review_takeout_form.do?takeout_num="+takeNum+"&b_id="+bId, "리뷰 작성", "width=520px,height=751px");
//})
=> 포장 리뷰 작성 및 수정 폼 - 팝업 구현 (방법은 주석으로 작성완료. 혜림님 참고하시면 됩니다.)

EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/BStoreMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/GUserMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/BStoreController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BStoreDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BStoreDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/BStoreDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/table.sql, EateryZip/src/main/webapp/WEB-INF/views/home.jsp, EateryZip/src/main/webapp/WEB-INF/views/store/store_insertform.jsp
보완 : 이미지테이블에서 이미지 수정, 스크랩내역, 포장내역 , 예약내역, css
=> checkKeyword추가 및 메인페이지 검색기능,이미지 db 저장 구현

EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/BStoreMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/ReviewMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/ReviewController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/UserController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BStoreDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BStoreDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/ReviewDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/ReviewDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/ReviewDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreServiceImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/ReviewService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/ReviewServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/eatery/ajax_detail.jsp, EateryZip/src/main/webapp/WEB-INF/views/eatery/detail.jsp, EateryZip/src/main/webapp/WEB-INF/views/home.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/reserve_List.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/review_reservation_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/review_takeout_form.jsp
예약 리뷰 작성/수정 폼 구현,리뷰(최신/인기 정렬, 사진리뷰 필터) sql문, 리뷰 키워드 나열, 리뷰리스트 sql문에 리뷰 추천 유무 추가, 리뷰 추천 서비스(미연결),리뷰 detail 기본 html 완성, 
앞으로 해야할 일 : 
1. 필터에 따른 리뷰 리스트 & 페이지네이션 ajax 처리
2. 리뷰 추천 기능 html에 연결
3. 메뉴폼 가격 유효성 검사
4. 미완성 list page 기능 구현....
=> 예약 리뷰 폼, 리뷰(최신/인기 정렬, 사진리뷰 필터) sql문, 리뷰 키워드 나열, 리뷰리스트 sql문에 리뷰 추천 유무 추가,리뷰 추천 서비스(미연결),리뷰 detail 기본 html 완성

EateryZip/src/main/java/com/sixnicorn/eateryzip/filter/LoginIFilter.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/BStoreMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/ReviewMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/BStoreController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BStoreDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BStoreDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/ReviewDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/ReviewDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/ReviewGoodDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreServiceImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/ReviewService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/ReviewServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/eatery/ajax_detail.jsp, EateryZip/src/main/webapp/WEB-INF/views/eatery/detail.jsp, EateryZip/src/main/webapp/navbar/header/navbar.jsp
상세페이지 css, 필터 2종(최신/인기 정렬 필터 + 사진 리뷰 필터 ) ajax, 페이징 ajax 처리, 예약/포장 폼 스크롤시 화면 고정,리뷰 추천/취소 구현,3가지 슬라이드 보완 및 완성(동적 버튼 노출)
=> 상세페이지 css, 필터 2종(최신/인기 정렬 필터 + 사진 리뷰 필터 ) ajax, 페이징 ajax 처리, 예약/포장 폼 스크롤시 화면 고정,리뷰 추천/취소 구현,3가지 슬라이드 보완 및 완성(동적 버튼 노출) 

EateryZip/src/main/java/com/sixnicorn/eateryzip/filter/LoginIFilter.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/BStoreMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/GUserMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/BStoreController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BStoreDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/BStoreDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/eatery/list.jsp, EateryZip/src/main/webapp/WEB-INF/views/home.jsp
=> 리스트 필터링 및 아래 페이징 처리 기능 구현

EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/BStoreMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/GUserMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/BStoreController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/UserController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BStoreDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BStoreDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/GUserDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/GUserDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/BStoreDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/TakeoutDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreServiceImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/table.sql, EateryZip/src/main/webapp/WEB-INF/views/home.jsp, EateryZip/src/main/webapp/WEB-INF/views/store/store_insertform.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_mypage/b_mypage.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_mypage/b_mypage_updateform.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_delete.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/g_mypage.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/g_mypage_updateform.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/takeout_list.jsp, EateryZip/src/main/webapp/navbar/footer/footer.jsp, EateryZip/src/main/webapp/navbar/header/navbar.jsp, EateryZip/src/main/webapp/navbar/header/navbar_list.jsp
=> 메인페이지, 포장내역, navbar, footer, 개인정보 프로필 업데이트

EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/BStoreMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/BStoreController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/eatery/list.jsp, EateryZip/src/main/webapp/navbar/header/navbar.jsp
리스트 필터링 완료 다만 (편의사항 중복처리 필요)
아래 페이징 처리 할게요.
=> 리스트 필터링 완료 다만 (편의사항 중복처리 필요)

EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/BStoreMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/BStoreDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BStoreServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/eatery/detail.jsp, EateryZip/src/main/webapp/WEB-INF/views/eatery/list.jsp, EateryZip/src/main/webapp/navbar/header/navbar.jsp, EateryZip/src/main/webapp/navbar/header/navbar_list.jsp
공통 부분 수정한 것 : TakeoutDto 수정, getlist mapper 수정
=> [리스트] 음식점 스크랩,CSS,각 인기 키워드 3개 추출 및 삽입,인기순 정렬

EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/BStoreDto.java, EateryZip/src/main/webapp/WEB-INF/table.sql, EateryZip/src/main/webapp/WEB-INF/views/eatery/detail.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_change_pwd_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_find_id_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_find_pwd_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_login_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_signup_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_change_pwd_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_find_id_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_find_pwd_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_login_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_signup_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/select_signup_form.jsp
=> Detail 지도 구현 및 각 .jsp 폰트변경

EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/BUserMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/GUserMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/UserController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BStoreDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BUserDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/BUserDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/GUserDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/GUserDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BUserService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/BUserServiceImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/users/b_login_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_mypage/b_mypage.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_login_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/g_mypage.jsp
=> 비즈니스 , 회원 회원탈퇴기능구현

EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserServiceImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/TakeOutServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/eatery/takeout_info_insertform.jsp, EateryZip/src/main/webapp/navbar/header/navbar.jsp
아직은 수정하고나서 로그아웃해야지 그때부터 제대로 적용되요.
이곳저곳 손 봐야할 곳이 있는 것 같은데 내일 다 체크해서 수정할게요.
=> sessio에 profile 가져가도록 설정 Css 부탁드려요.

EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserServiceImpl.java
로그아웃, 비밀번호 수정시 아이디와 함께 프로필 사진 변경되도록 코드보완
=> 개인정보 수정하면 프로필에 바로 저장하도록 수정 

EateryZip/src/main/java/com/sixnicorn/eateryzip/mybatis/GUserMapper.xml, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/controller/UserController.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/GUserDao.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dao/GUserDaoImpl.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/dto/EateryScrapDto.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserService.java, EateryZip/src/main/java/com/sixnicorn/eateryzip/user/service/GUserServiceImpl.java, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/scrap_List.jsp
=> 일반유저 스크랩리스트 페이지 완성

EateryZip/src/main/webapp/WEB-INF/table.sql, EateryZip/src/main/webapp/WEB-INF/views/users/b_mypage/b_mypage.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/g_mypage.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/g_mypage_updateform.jsp
테이블sql에 ex_keyword부분 varchar2(100)->varchar2(200) 수정
일반유저 일단 유효성검사 간단하게 삽입
비즈니스 및 일반유저 장문일경우 폼이 넘쳐서 수정
=> 비즈니스 및 일반유저 장문일경우 폼이 넘쳐서 수정

EateryZip/src/main/webapp/WEB-INF/views/users/b_login_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_login_form.jsp
=> 로그인 실패 문구 수정

EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/reserve_List.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/scrap_List.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_mypage/takeout_list.jsp
=> 타이틀 글씨체및 예약내역에서 내용보는 버튼 설정

EateryZip/src/main/webapp/WEB-INF/views/eatery/detail.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/b_signup_form.jsp, EateryZip/src/main/webapp/WEB-INF/views/users/g_signup_form.jsp
Detail.js 지도 위치 변경
회원가입취소버튼 색 수정
=> Detail.js 지도 위치 변경 , 회원가입취소버튼 색 수정

EateryZip/src/main/webapp/WEB-INF/views/users/b_mypage/b_reservation_list.jsp
=> 비즈니스 예약내역볼때경로 오류 수정
